[build]
command = "npm run build"
outputDirectory = "dist"

[build.environment]
NODE_VERSION = "18"
VITE_EMAILJS_SERVICE_ID = "service_k2y51le"
VITE_EMAILJS_TEMPLATE_ID = "template_ylgq1uk"
VITE_EMAILJS_PUBLIC_KEY = "nmSkiqk2c-XdzhiYo"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200
